# These are supported funding model platforms

github: rawnly
# patreon: # Replace with a single Patreon username
# open_collective: # Replace with a single Open Collective username
# issuehunt: rawnly
custom: [
  'https://www.notion.so/?r=a343a2c1fbd9490c85dd67fe7576debc', 
  'https://www.stickermule.com/it/unlock?ref_id=6392580701&utm_medium=link&utm_source=invite', 
  'https://m.do.co/c/f88cef1a6e56',
  'https://plant.treeware.earth/splash-cli/splash-cli'
]
