# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
project_name: splash
universal_binaries:
  - name_template: splash
    replace: true
before:
  hooks:
    - go mod tidy
builds:
  - binary: splash
    env:
      - CGO_ENABLED=0
    ldflags:
      - -X "github.com/rawnly/splash-cli/cmd/root.version={{ .Version }}"
      - -X "github.com/rawnly/splash-cli/cmd/root.commit={{ .Commit }}"
      - -s -w -X "main.ClientId={{ .Env.UNSPLASH_CLIENT_ID }}"
      - -s -w -X "main.ClientSecret={{ .Env.UNSPLASH_CLIENT_SECRET }}"
    goos:
      - linux
      - windows
      - darwin
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
release:
  github:
    owner: splash-cli
    name: splash-cli
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
